# Generated by Django 3.0.6 on 2020-05-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imageuploader_profile',
        ),
    ]
